# Generated by Django 6.0.7 on 2026-07-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tool_department_tool_first_calibration_date_tool_gpn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='alert_level',
            field=models.CharField(choices=[('none', 'Aucune'), ('green', 'Vert'), ('yellow', 'Jaune'), ('red', 'Rouge')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='tool',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='validation_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='toolhistory',
            name='field_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='toolhistory',
            name='new_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toolhistory',
            name='old_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toolhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('calibrated', 'Calibrated'), ('status_changed', 'Status Changed'), ('deleted', 'Deleted')], max_length=20),
        ),
    ]
