# Generated by Django 6.0.7 on 2026-08-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_tool_alert_level_tool_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='serial_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='first_calibration_date',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='tool',
            name='calibration_tracability',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='connector_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='first_calibration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='lp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='name_surname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='order_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='reception_tracability',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='tool_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='tool_index',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
