# Generated by Django 5.2.17 on 2026-08-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_rename_serial_number_tool_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='calibration_pdf',
            field=models.FileField(blank=True, null=True, upload_to='calibration_pdfs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='tool',
            name='calibration_pdf_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='reception_pdf',
            field=models.FileField(blank=True, null=True, upload_to='reception_pdfs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='tool',
            name='reception_pdf_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toolhistory',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='toolhistory',
            name='file_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='toolhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('calibrated', 'Calibrated'), ('status_changed', 'Status Changed'), ('deleted', 'Deleted'), ('calibration_tracability_uploaded', 'Calibration Tracability Uploaded'), ('reception_tracability_uploaded', 'Reception Tracability Uploaded')], max_length=50),
        ),
    ]
