# Generated by Django 5.2.17 on 2026-08-08 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_tool_calibration_pdf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='calibration_pdf_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration_pdf_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tool',
            name='reception_pdf_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reception_pdf_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toolhistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toolhistory',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='toolhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('calibrated', 'Calibrated'), ('status_changed', 'Status Changed'), ('deleted', 'Deleted'), ('calibration_tracability_uploaded', 'Calibration Tracability Uploaded'), ('reception_tracability_uploaded', 'Reception Tracability Uploaded'), ('calibration_tracability_deleted', 'Calibration Tracability Deleted'), ('reception_tracability_deleted', 'Reception Tracability Deleted')], max_length=50),
        ),
        migrations.AlterField(
            model_name='toolhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='toolhistory',
            index=models.Index(fields=['tool', '-created_at'], name='tools_toolh_tool_id_ef7e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='toolhistory',
            index=models.Index(fields=['user', '-created_at'], name='tools_toolh_user_id_87d868_idx'),
        ),
        migrations.AddIndex(
            model_name='toolhistory',
            index=models.Index(fields=['action'], name='tools_toolh_action_928f4e_idx'),
        ),
    ]
